/*
Copyright © 2025 Benny Powers <web@bennypowers.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
package export

import (
	"bytes"
	"fmt"
	"strings"
)

var _ FrameworkExporter = (*VueExporter)(nil)

// VueExporter generates Vue SFC wrapper components.
type VueExporter struct{}

func (v *VueExporter) Name() string { return "vue" }

func (v *VueExporter) ExportElement(element ExportElement, cfg FrameworkExportConfig) (map[string]string, error) {
	componentName := TagNameToComponentName(element.TagName, cfg.StripPrefix)

	tmpl, err := getVueTemplate()
	if err != nil {
		return nil, fmt.Errorf("parsing vue template: %w", err)
	}

	data := struct {
		ExportElement
		ComponentName string
	}{
		ExportElement: element,
		ComponentName: componentName,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing vue template for %s: %w", element.TagName, err)
	}

	filename := componentName + ".vue"
	return map[string]string{filename: buf.String()}, nil
}

func (v *VueExporter) ExportIndex(elements []ExportElement, cfg FrameworkExportConfig) (map[string]string, error) {
	var b strings.Builder
	b.WriteString("// Generated by cem export - do not edit\n")
	for _, elem := range elements {
		name := TagNameToComponentName(elem.TagName, cfg.StripPrefix)
		fmt.Fprintf(&b, "export { default as %s } from './%s.vue';\n", name, name)
	}
	return map[string]string{"index.ts": b.String()}, nil
}
