version: 2
project_name: cem

builds:
  - main: .
    binary: cem
    ldflags:
      - -X 'bennypowers.dev/cem/internal/version.Version={{.Version}}'
      - -X 'bennypowers.dev/cem/internal/version.GitCommit={{.Commit}}'
      - -X 'bennypowers.dev/cem/internal/version.GitTag={{.Tag}}'
      - -X 'bennypowers.dev/cem/internal/version.BuildTime={{.Date}}'
      - -X 'bennypowers.dev/cem/internal/version.GitDirty={{if .IsGitDirty}}dirty{{end}}'

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - dist/cem*
    format: tar.gz

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: bennypowers
    name: cem

changelog: {}
