version: 2

builds:
  - id: cem
    binary: cem
    main: ./cmd/cem
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    hooks:
      pre: make build-all

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: bennypowers
    name: cem
