project_name: cem

builds:
  - id: cem-amd64
    main: .
    binary: cem
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=gcc
    hooks:
      pre:
        - go generate ./...
  - id: cem-arm64
    main: .
    binary: cem
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    hooks:
      pre:
        - go generate ./...

archives:
  - id: cem-archive
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - dist/cem*
    format: tar.gz

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: bennypowers
    name: cem

changelog: {}
