version: 2
project_name: cem

builds:
  - main: .
    binary: cem
    env:
      - CGO_ENABLED=1
      - CC={{.Env.CC}}
    hooks:
      pre:
        - go generate ./...

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - dist/cem*
    format: tar.gz

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: bennypowers
    name: cem

changelog: {}
