<!-- Generated by cem export - do not edit -->
<script setup lang="ts">
import 'my-package/elements/my-button.js';

export interface ButtonProps {
  /** Button variant style */
  variant?: 'primary' | 'secondary';
  /** Whether the button is disabled */
  disabled?: boolean;
  /** Arbitrary data payload */
  data?: Record<string, unknown>;
}

const props = defineProps<ButtonProps>();

const emit = defineEmits<{
  'my-click': [event: CustomEvent<{ value: string }>];
}>();
</script>

<template>
  <my-button
    :variant="props.variant"
    :disabled="props.disabled ? '' : undefined"
    :data="props.data"
    @my-click="emit('my-click', $event as CustomEvent<{ value: string }>)">
    <slot />
    <slot name="icon" />
  </my-button>
</template>
