// Generated by cem export - do not edit
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
  AfterViewInit,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import 'my-package/elements/my-button.js';

/** A button component */
@Component({
  selector: 'my-button',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
    <ng-content select="[slot=icon]"></ng-content>
  `,
})
export class ButtonComponent implements AfterViewInit, OnChanges, OnDestroy {
  @ViewChild('el', { static: true }) private elRef!: ElementRef<HTMLElement>;
  /** Button variant style */
  @Input() variant?: 'primary' | 'secondary';
  /** Whether the button is disabled */
  @Input() disabled: boolean = false;
  /** Arbitrary data payload */
  @Input() data?: Record<string, unknown>;
  /** Fired when the button is clicked */
  @Output() myClick = new EventEmitter<CustomEvent<{ value: string }>>();

  private listeners: (() => void)[] = [];

  ngAfterViewInit(): void {
    const el = this.elRef.nativeElement;
    {
      const handler = (event: Event) => this.myClick.emit(event as CustomEvent<{ value: string }>);
      el.addEventListener('my-click', handler);
      this.listeners.push(() => el.removeEventListener('my-click', handler));
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    const el = this.elRef?.nativeElement;
    if (!el) return;
    if (changes['data']) (el as any).data = this.data;
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
    this.listeners = [];
  }
}
