// Generated by cem export - do not edit
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

import { ButtonComponent } from './Button.component';

@NgModule({
  imports: [
    ButtonComponent,
  ],
  exports: [
    ButtonComponent,
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ComponentsModule {}
