/*
Copyright © 2025 Benny Powers <web@bennypowers.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
*/

package serve

import (
	"context"
	"fmt"

	litssr "bennypowers.dev/lit-ssr-go"
	"bennypowers.dev/cem/serve/middleware/routes"
)

// litSSRRenderer is the interface for rendering HTML with Lit SSR.
type litSSRRenderer interface {
	RenderHTML(ctx context.Context, html string) (string, error)
	Close(ctx context.Context) error
}

// TODO: replace with dogfooded cem generate manifest
// Generated from: ls serve/elements/*/
var chromeElements = []string{
	"cem-color-scheme-toggle",
	"cem-connection-status",
	"cem-detail-panel",
	"cem-drawer",
	"cem-health-panel",
	"cem-manifest-browser",
	"cem-reconnection-content",
	"cem-serve-chrome",
	"cem-serve-demo",
	"cem-serve-knob-group",
	"cem-serve-knobs",
	"cem-transform-error-overlay",
	"cem-virtual-tree",
	"pf-v6-alert",
	"pf-v6-alert-group",
	"pf-v6-badge",
	"pf-v6-button",
	"pf-v6-card",
	"pf-v6-drawer",
	"pf-v6-dropdown",
	"pf-v6-expandable-section",
	"pf-v6-form",
	"pf-v6-form-field-group",
	"pf-v6-form-group",
	"pf-v6-form-label",
	"pf-v6-label",
	"pf-v6-masthead",
	"pf-v6-menu",
	"pf-v6-menu-item",
	"pf-v6-modal",
	"pf-v6-nav-group",
	"pf-v6-nav-item",
	"pf-v6-nav-link",
	"pf-v6-nav-list",
	"pf-v6-navigation",
	"pf-v6-page",
	"pf-v6-page-main",
	"pf-v6-page-sidebar",
	"pf-v6-popover",
	"pf-v6-select",
	"pf-v6-skip-to-content",
	"pf-v6-switch",
	"pf-v6-tab",
	"pf-v6-tabs",
	"pf-v6-text-input",
	"pf-v6-text-input-group",
	"pf-v6-toggle-group",
	"pf-v6-toggle-group-item",
	"pf-v6-toolbar",
	"pf-v6-toolbar-group",
	"pf-v6-toolbar-item",
	"pf-v6-tree-item",
	"pf-v6-tree-view",
}

// initLitSSR initializes the Lit SSR renderer with all embedded chrome
// element component sources.
func (s *Server) initLitSSR(ctx context.Context) error {
	source, err := buildComponentSource()
	if err != nil {
		return fmt.Errorf("build component source: %w", err)
	}

	if source == "" {
		s.logger.Warning("No Lit element sources found, SSR disabled")
		return nil
	}

	renderer, err := litssr.NewWithElements(ctx, source, chromeElements, 0)
	if err != nil {
		return fmt.Errorf("init lit-ssr renderer: %w", err)
	}

	s.litSSR = renderer
	s.logger.Info("Lit SSR renderer initialized")
	return nil
}

// buildComponentSource reads the SSR bundle from the embedded FS.
// This is a single self-contained JS file with all components and lit
// bundled together, generated by `go generate`.
func buildComponentSource() (string, error) {
	data, err := routes.TemplatesFS.ReadFile("templates/ssr-bundle.js")
	if err != nil {
		return "", fmt.Errorf("read ssr-bundle.js: %w", err)
	}
	return string(data), nil
}
