/*
Copyright © 2025 Benny Powers <web@bennypowers.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
*/

package serve

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"testing"

	litssr "bennypowers.dev/lit-ssr-wasm/go"
	M "bennypowers.dev/cem/manifest"
	"bennypowers.dev/cem/serve/middleware/routes"
)

// litSSRRenderer is the interface for rendering HTML with Lit SSR.
type litSSRRenderer interface {
	RenderHTML(ctx context.Context, html string) (string, error)
	Close(ctx context.Context) error
}

//go:embed elements/patternfly/custom-elements.json elements/chrome/custom-elements.json
var chromeManifestsFS embed.FS

// initLitSSR initializes the Lit SSR renderer from pre-compiled
// QuickJS bytecode embedded in the binary. Bytecode loading skips
// the JS parse+compile phase, reducing init from ~1s to ~100ms.
func (s *Server) initLitSSR(ctx context.Context) error {
	// Skip SSR in tests - no test exercises SSR and init adds ~1s per server
	if testing.Testing() {
		return nil
	}

	elements := discoverChromeElements()
	if len(elements) == 0 {
		s.logger.Warning("No custom elements found in manifests, SSR disabled")
		return nil
	}

	var renderer *litssr.Renderer

	// Try bytecode first (fast path: ~100ms vs ~1s for source eval)
	if bytecode, err := routes.TemplatesFS.ReadFile("templates/ssr-bundle.qbc"); err == nil && len(bytecode) > 0 {
		renderer, err = litssr.NewFromBytecode(ctx, bytecode, elements, 1)
		if err != nil {
			s.logger.Warning("Bytecode init failed, falling back to source: %v", err)
			renderer = nil
		}
	}

	// Fallback to source eval
	if renderer == nil {
		source, err := buildComponentSource()
		if err != nil || source == "" {
			s.logger.Warning("No Lit element sources found, SSR disabled")
			return nil
		}
		renderer, err = litssr.NewWithElements(ctx, source, elements, 1)
		if err != nil {
			return fmt.Errorf("init lit-ssr renderer: %w", err)
		}
	}

	s.litSSR = renderer
	s.logger.Info("Lit SSR renderer initialized with %d elements", len(elements))
	return nil
}

// discoverChromeElements reads tag names from the embedded manifests
// generated by cem generate during go:generate.
func discoverChromeElements() []string {
	manifests := []string{
		"elements/patternfly/custom-elements.json",
		"elements/chrome/custom-elements.json",
	}

	var tags []string
	for _, path := range manifests {
		data, err := chromeManifestsFS.ReadFile(path)
		if err != nil {
			continue
		}
		var pkg M.Package
		if err := json.Unmarshal(data, &pkg); err != nil {
			continue
		}
		tags = append(tags, pkg.GetAllTagNames()...)
	}
	return tags
}

// buildComponentSource reads the SSR bundle from the embedded FS.
func buildComponentSource() (string, error) {
	data, err := routes.TemplatesFS.ReadFile("templates/ssr-bundle.js")
	if err != nil {
		return "", fmt.Errorf("read ssr-bundle.js: %w", err)
	}
	return string(data), nil
}
