/*
Copyright © 2025 Benny Powers <web@bennypowers.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
*/

package serve

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"

	litssr "github.com/bennypowers/lit-ssr-wasm/go"
	M "bennypowers.dev/cem/manifest"
	"bennypowers.dev/cem/serve/middleware/routes"
)

// litSSRRenderer is the interface for rendering HTML with Lit SSR.
type litSSRRenderer interface {
	RenderHTML(ctx context.Context, html string) (string, error)
	Close(ctx context.Context) error
}

//go:embed elements/patternfly/custom-elements.json elements/chrome/custom-elements.json
var chromeManifestsFS embed.FS

// initLitSSR initializes the Lit SSR renderer with the pre-bundled
// SSR source embedded in the binary. Element tag names are read from
// the generated custom-elements.json manifests.
func (s *Server) initLitSSR(ctx context.Context) error {
	source, err := buildComponentSource()
	if err != nil {
		return fmt.Errorf("build component source: %w", err)
	}

	if source == "" {
		s.logger.Warning("No Lit element sources found, SSR disabled")
		return nil
	}

	elements := discoverChromeElements()
	if len(elements) == 0 {
		s.logger.Warning("No custom elements found in manifests, SSR disabled")
		return nil
	}

	// Single worker is sufficient for the dev server (one user, ~3500 renders/sec).
	// This keeps init to ~1s instead of ~6s with NumCPU workers.
	renderer, err := litssr.NewWithElements(ctx, source, elements, 1)
	if err != nil {
		return fmt.Errorf("init lit-ssr renderer: %w", err)
	}

	s.litSSR = renderer
	s.logger.Info("Lit SSR renderer initialized with %d elements", len(elements))
	return nil
}

// discoverChromeElements reads tag names from the embedded manifests
// generated by cem generate during go:generate.
func discoverChromeElements() []string {
	manifests := []string{
		"elements/patternfly/custom-elements.json",
		"elements/chrome/custom-elements.json",
	}

	var tags []string
	for _, path := range manifests {
		data, err := chromeManifestsFS.ReadFile(path)
		if err != nil {
			continue
		}
		var pkg M.Package
		if err := json.Unmarshal(data, &pkg); err != nil {
			continue
		}
		tags = append(tags, pkg.GetAllTagNames()...)
	}
	return tags
}

// buildComponentSource reads the SSR bundle from the embedded FS.
func buildComponentSource() (string, error) {
	data, err := routes.TemplatesFS.ReadFile("templates/ssr-bundle.js")
	if err != nil {
		return "", fmt.Errorf("read ssr-bundle.js: %w", err)
	}
	return string(data), nil
}
