// Generated by cem export - do not edit
import React, { forwardRef, useRef, useEffect, type HTMLAttributes, type Ref } from 'react';
import 'my-package/elements/my-button.js';

export interface ButtonProps extends HTMLAttributes<HTMLElement> {
  /** Button variant style */
  variant?: 'primary' | 'secondary';
  /** Whether the button is disabled */
  disabled?: boolean;
  /** Arbitrary data payload */
  data?: Record<string, unknown>;
  /** Fired when the button is clicked */
  onMyClick?: (event: CustomEvent<{ value: string }>) => void;
}

/** A button component */
export const Button = forwardRef(function Button(
  props: ButtonProps,
  forwardedRef: Ref<HTMLElement>,
) {
  const innerRef = useRef<HTMLElement>(null);
  const ref = (forwardedRef ?? innerRef) as React.RefObject<HTMLElement>;

  const {
    variant,
    disabled,
    data,
    onMyClick,
    children,
    ...rest
  } = props;

  // Sync properties to the underlying element
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (variant !== undefined) (el as any).variant = variant;
    if (disabled !== undefined) (el as any).disabled = disabled;
    if (data !== undefined) (el as any).data = data;
  }, [ref, variant, disabled, data,]);

  // Bind event listeners
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const cleanups: (() => void)[] = [];
    if (onMyClick) {
      const handler = onMyClick as EventListener;
      el.addEventListener('my-click', handler);
      cleanups.push(() => el.removeEventListener('my-click', handler));
    }
    return () => cleanups.forEach(fn => { fn(); });
  }, [ref, onMyClick,]);

  return React.createElement(
    'my-button',
    {
      ...rest,
      ref,
    },
    children,
  );
});
