/*
Copyright © 2026 Benny Powers <web@bennypowers.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
package cmd

import (
	"bytes"
	"encoding/json"
	"sort"
	"strings"

	IC "bennypowers.dev/cem/internal/config"
	"bennypowers.dev/cem/internal/set"
	"gopkg.in/yaml.v3"
)

func marshalConfig(cfg *IC.CemConfig, format string, existingData []byte) ([]byte, error) {
	switch format {
	case "json":
		data, err := marshalConfigJSON(cfg)
		if err != nil {
			return nil, err
		}
		return data, nil
	case "jsonc":
		data, err := marshalConfigJSON(cfg)
		if err != nil {
			return nil, err
		}
		return append([]byte("// Generated by cem config init\n"), data...), nil
	default:
		return marshalConfigYAML(cfg, existingData)
	}
}

func marshalConfigJSON(cfg *IC.CemConfig) ([]byte, error) {
	var intermediate map[string]any
	raw, err := json.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	if json.Unmarshal(raw, &intermediate) != nil {
		return raw, nil
	}
	pruneJSONMap(intermediate)
	return json.MarshalIndent(intermediate, "", "  ")
}

func pruneJSONMap(m map[string]any) {
	for k, v := range m {
		if deprecatedConfigKeys.Has(k) || isZeroJSON(v) {
			delete(m, k)
			continue
		}
		if sub, ok := v.(map[string]any); ok {
			if isAllZeroJSONMap(sub) {
				delete(m, k)
				continue
			}
			pruneJSONMap(sub)
			if len(sub) == 0 {
				delete(m, k)
			}
		}
	}
}

func isAllZeroJSONMap(m map[string]any) bool {
	for _, v := range m {
		switch val := v.(type) {
		case nil:
		case string:
			if val != "" {
				return false
			}
		case float64:
			if val != 0 {
				return false
			}
		case bool:
			if val {
				return false
			}
		case []any:
			if len(val) > 0 {
				return false
			}
		case map[string]any:
			if !isAllZeroJSONMap(val) {
				return false
			}
		default:
			return false
		}
	}
	return true
}

func isZeroJSON(v any) bool {
	switch val := v.(type) {
	case nil:
		return true
	case string:
		return val == ""
	case float64:
		return val == 0
	case bool:
		return false
	case []any:
		return len(val) == 0
	case map[string]any:
		return len(val) == 0
	}
	return false
}

func marshalConfigYAML(cfg *IC.CemConfig, existingData []byte) ([]byte, error) {
	var node yaml.Node
	if err := node.Encode(cfg); err != nil {
		return nil, err
	}

	root := &node
	if node.Kind == yaml.DocumentNode && len(node.Content) > 0 {
		root = node.Content[0]
	}

	pruneYAMLNode(root)
	removeYAMLKeys(root, deprecatedConfigKeys)

	if len(existingData) > 0 {
		var existingNode yaml.Node
		if yaml.Unmarshal(existingData, &existingNode) == nil {
			existingRoot := &existingNode
			if existingNode.Kind == yaml.DocumentNode && len(existingNode.Content) > 0 {
				existingRoot = existingNode.Content[0]
			}
			reorderYAMLMapping(root, existingRoot)
		}
	}

	indent := detectIndent(existingData)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(indent)
	if err := enc.Encode(&node); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func reorderYAMLMapping(target, reference *yaml.Node) {
	if target.Kind != yaml.MappingNode || reference.Kind != yaml.MappingNode {
		return
	}

	refOrder := map[string]int{}
	for i := 0; i+1 < len(reference.Content); i += 2 {
		refOrder[reference.Content[i].Value] = i
	}

	type kv struct {
		key, val *yaml.Node
		refIdx   int
	}
	var ordered, appended []kv
	for i := 0; i+1 < len(target.Content); i += 2 {
		k := target.Content[i].Value
		if idx, ok := refOrder[k]; ok {
			ordered = append(ordered, kv{target.Content[i], target.Content[i+1], idx})
		} else {
			appended = append(appended, kv{target.Content[i], target.Content[i+1], -1})
		}
	}

	sort.Slice(ordered, func(a, b int) bool {
		return ordered[a].refIdx < ordered[b].refIdx
	})

	target.Content = make([]*yaml.Node, 0, 2*(len(ordered)+len(appended)))
	for _, item := range ordered {
		target.Content = append(target.Content, item.key, item.val)
		if item.val.Kind == yaml.MappingNode {
			refVal := reference.Content[item.refIdx+1]
			if refVal.Kind == yaml.MappingNode {
				reorderYAMLMapping(item.val, refVal)
			}
		}
	}
	for _, item := range appended {
		target.Content = append(target.Content, item.key, item.val)
	}
}

var deprecatedConfigKeys = set.NewSet("verbose")

func removeYAMLKeys(node *yaml.Node, keys set.Set[string]) {
	if node.Kind != yaml.MappingNode {
		return
	}
	var kept []*yaml.Node
	for i := 0; i+1 < len(node.Content); i += 2 {
		if !keys.Has(node.Content[i].Value) {
			kept = append(kept, node.Content[i], node.Content[i+1])
		}
	}
	node.Content = kept
}

func pruneYAMLNode(node *yaml.Node) {
	if node.Kind != yaml.MappingNode {
		return
	}

	var kept []*yaml.Node
	for i := 0; i+1 < len(node.Content); i += 2 {
		key := node.Content[i]
		val := node.Content[i+1]

		if isZeroYAMLNode(val) {
			continue
		}

		if val.Kind == yaml.MappingNode {
			if isAllZeroMapping(val) {
				continue
			}
			pruneYAMLNode(val)
			if len(val.Content) == 0 {
				continue
			}
		}

		kept = append(kept, key, val)
	}
	node.Content = kept
}

func isAllZeroMapping(node *yaml.Node) bool {
	if node.Kind != yaml.MappingNode {
		return false
	}
	for i := 1; i < len(node.Content); i += 2 {
		v := node.Content[i]
		switch v.Kind {
		case yaml.ScalarNode:
			switch v.Tag {
			case "!!null":
				// nil pointers are zero
			case "!!bool":
				if v.Value != "false" {
					return false
				}
			case "!!int", "!!float":
				if v.Value != "0" {
					return false
				}
			default:
				if v.Value != "" {
					return false
				}
			}
		case yaml.SequenceNode:
			if len(v.Content) > 0 {
				return false
			}
		case yaml.MappingNode:
			if !isAllZeroMapping(v) {
				return false
			}
		default:
			return false
		}
	}
	return true
}

func isZeroYAMLNode(n *yaml.Node) bool {
	switch n.Kind {
	case yaml.ScalarNode:
		if n.Tag == "!!null" {
			return true
		}
		if n.Tag == "!!bool" {
			return false
		}
		if n.Tag == "!!int" || n.Tag == "!!float" {
			return n.Value == "0"
		}
		return n.Value == ""
	case yaml.SequenceNode:
		return len(n.Content) == 0
	case yaml.MappingNode:
		return len(n.Content) == 0
	case yaml.AliasNode:
		return n.Alias != nil && isZeroYAMLNode(n.Alias)
	}
	return n.Tag == "!!null"
}

func hasConfigKey(data []byte, key string) bool {
	var m map[string]any
	if yaml.Unmarshal(data, &m) == nil {
		_, ok := m[key]
		return ok
	}
	stripped := IC.StripComments(data)
	if json.Unmarshal(stripped, &m) == nil {
		_, ok := m[key]
		return ok
	}
	return false
}

func detectIndent(data []byte) int {
	if len(data) == 0 {
		return 2
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		trimmed := strings.TrimLeft(line, " ")
		indent := len(line) - len(trimmed)
		if indent > 0 {
			return indent
		}
	}
	return 2
}
