name: Benchmark Analyzers

on:
  workflow_dispatch:
    inputs:
      runs:
        description: 'Number of benchmark runs'
        required: false
        default: '100'
  push:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install and build analyzers
        run: |
          cd analyzer-benchmarks
          npm ci
          cd .. && go build && cd analyzer-benchmarks

      - name: Run Analyzers and Collect Results
        id: benchmark
        run: ./benchmark.sh ${{ github.event.inputs.runs || 25 }}

      - name: Generate static site
        run: |
          cd analyzer-benchmarks
          npm run generate-site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: analyzer-benchmarks/site
