name: Benchmark Analyzers

on:
  workflow_dispatch:
    inputs:
      runs:
        description: 'Number of benchmark runs'
        required: false
        default: '100'
  push:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: make build
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: |
          cd analyzer-benchmarks
          npm ci
          ./benchmark.sh ${{ github.event.inputs.runs || 100 }}
          npm run generate-site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: analyzer-benchmarks/site
