name: Lint
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
        env:
          GOTOOLCHAIN: auto
          GOEXPERIMENT: jsonv2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.65.1
          only-new-issues: true
          args: --verbose
